#!/usr/bin/env sh

# Kindle LLM dashboard local settings.
# This file is sourced by the launcher scripts.

export TIMEZONE=${TIMEZONE:-"Asia/Taipei"}
export WIFI_TEST_IP=${WIFI_TEST_IP:-1.1.1.1}

export DASHBOARD_URL=${DASHBOARD_URL:-"https://your-project.vercel.app/api/dashboard?profile=dp75sdi&managed=true"}
export REMOTE_CONFIG_URL=${REMOTE_CONFIG_URL:-"https://your-project.vercel.app/api/device-config?profile=dp75sdi"}

export REFRESH_INTERVAL_SECS=${REFRESH_INTERVAL_SECS:-720}
export FULL_DISPLAY_REFRESH_RATE=${FULL_DISPLAY_REFRESH_RATE:-1}

export KUAL_SETTLE_DELAY_SECS=${KUAL_SETTLE_DELAY_SECS:-3}
export CLEAR_BEFORE_DISPLAY=${CLEAR_BEFORE_DISPLAY:-false}
export STOP_KINDLE_UI=${STOP_KINDLE_UI:-false}
export ALLOW_FRAMEWORK_STOP=${ALLOW_FRAMEWORK_STOP:-false}
export UI_SETTLE_DELAY_SECS=${UI_SETTLE_DELAY_SECS:-2}
export HIDE_KINDLE_CHROME=${HIDE_KINDLE_CHROME:-true}
export FREEZE_KINDLE_WINDOW_MANAGER=${FREEZE_KINDLE_WINDOW_MANAGER:-true}
export POWER_BUTTON_RESTORES_KINDLE=${POWER_BUTTON_RESTORES_KINDLE:-true}

export DASHBOARD_USE_RTC=${DASHBOARD_USE_RTC:-false}
export LOW_BATTERY_REPORTING=${LOW_BATTERY_REPORTING:-false}
export LOW_BATTERY_THRESHOLD_PERCENT=${LOW_BATTERY_THRESHOLD_PERCENT:-10}
